import type { Course } from "@/types/course.type";

// Fake course data (replace with API data later)
export const COURSES: Course[] = [
  {
    id: "c1",
    title: "Learn Figma from Basic",
    instructor: "yustelsed studio",
    image: "/asset/courses/c1.jpg",
    category: "UI/UX Design",
    level: "Beginner",
    lessons: 17,
    duration: "2 hours 34 mins",
    comments: 89,
    rating: 4.5,
    students: "5K+",
    price: 25,
    priceUnit: "/course",
  },
  {
    id: "c2",
    title: "Build Digital Asset",
    instructor: "yustelsed studio",
    image: "/asset/courses/c2.jpg",
    category: "Graphic Design",
    level: "Beginner",
    lessons: 17,
    duration: "2 hours 34 mins",
    comments: 89,
    rating: 4.5,
    students: "5K+",
    price: 25,
    priceUnit: "/course",
  },
  {
    id: "c3",
    title: "The Power of Big Data",
    instructor: "yustelsed studio",
    image: "/asset/courses/c3.jpg",
    category: "Data Science",
    level: "Beginner",
    lessons: 17,
    duration: "2 hours 34 mins",
    comments: 89,
    rating: 4.5,
    students: "5K+",
    price: 25,
    priceUnit: "/course",
  },
  {
    id: "c4",
    title: "Balancing Productivity and Life",
    instructor: "yustelsed studio",
    image: "/asset/courses/c4.jpg",
    category: "Productivity",
    level: "Beginner",
    lessons: 17,
    duration: "2 hours 34 mins",
    comments: 89,
    rating: 4.5,
    students: "5K+",
    price: 25,
    priceUnit: "/course",
  },
  {
    id: "c5",
    title: "Mastering Money Management",
    instructor: "yustelsed studio",
    image: "/asset/courses/c5.jpg",
    category: "Freelance & Entrepreneurship",
    level: "Beginner",
    lessons: 17,
    duration: "2 hours 34 mins",
    comments: 89,
    rating: 4.5,
    students: "5K+",
    price: 25,
    priceUnit: "/course",
  },
  {
    id: "c6",
    title: "From Idea to Startup Success",
    instructor: "yustelsed studio",
    image: "/asset/courses/c6.jpg",
    category: "Freelance & Entrepreneurship",
    level: "Beginner",
    lessons: 17,
    duration: "2 hours 34 mins",
    comments: 89,
    rating: 4.5,
    students: "5K+",
    price: 25,
    priceUnit: "/course",
  },
];
